#!/bin/sh
set -e

INPUT_DIR="./kernel-bin"
PKG_NAME="linux-custom"
MAINTAINER="User <user@localhost>"

apk add alpine-sdk abuild woas

if [ ! -d "$HOME/.abuild" ] || [ -z "$(ls "$HOME"/.abuild/*.rsa 2>/dev/null)" ]; then
    echo ">>> gen pack key..."
    abuild-keygen -a -n
fi

if [ ! -d "$INPUT_DIR" ]; then
    exit 2
fi

KERNEL_IMG=$(find "$INPUT_DIR/boot" -name "vmlinuz-*" | head -n 1)
if [ -z "$KERNEL_IMG" ]; then
    exit 2
fi

FILENAME=$(basename "$KERNEL_IMG")
VERSION_RAW=$(echo "$FILENAME" | sed 's/vmlinuz-//')
PKG_VER="${VERSION_RAW%%-*}"
PKG_REL=0

echo ">>> build version: $PKG_VER"

BUILD_ROOT="./build-area/$PKG_NAME"
rm -rf "$BUILD_ROOT"
mkdir -p "$BUILD_ROOT"

echo ">>> copy kernel..."
cp -r "$INPUT_DIR" "$BUILD_ROOT/kernel-bin"

cd "$BUILD_ROOT"

cat <<EOF > APKBUILD
# Generated by pack-kernel.sh
pkgname="$PKG_NAME"
pkgver="$PKG_VER"
pkgrel=$PKG_REL
pkgdesc="Custom pre-built Linux kernel $VERSION_RAW"
url="https://kernel.org"
arch="all"
license="GPL-2.0-only"
options="!check !strip !tracedeps"
depends="mkinitfs kmod"
makedepends=""
source=""

package() {
    local external_src="\$startdir/kernel-bin"
    msg "Copying files from \$external_src..."
    
    mkdir -p "\$pkgdir/boot"
    if [ -d "\$external_src/boot" ]; then
        cp -a "\$external_src/boot/"* "\$pkgdir/boot/"
        cp "\$pkgdir/boot/"vmlinuz* "\$pkgdir/boot/Image"
    fi
    
    mkdir -p "\$pkgdir/lib/modules"
    if [ -d "\$external_src/lib/modules" ]; then
        cp -a "\$external_src/lib/modules/"* "\$pkgdir/lib/modules/"
    fi
}
EOF

echo ">>> gen checksum..."
abuild checksum

echo ">>> start build..."

abuild -r -d -F || true

APK_PATH="$HOME/packages/$(uname -m)/$PKG_NAME-$PKG_VER-r$PKG_REL.apk"

echo "apk add --allow-untrusted $APK_PATH"

