#!/bin/sh
set -e

INPUT_DIR="./build/kernel-pkg/kernel-bin"
PKG_NAME="linux-custom"
MAINTAINER="User <user@localhost.lan>"

if [ ! -d "$HOME/.abuild" ] || [ -z "$(ls "$HOME"/.abuild/*.rsa 2>/dev/null)" ]; then
    echo ">>> gen pack key..."
    abuild-keygen -a -n
    cp ~/.abuild/*.rsa.pub /etc/apk/keys
    cp ~/.abuild/*.rsa.pub ../pkg-key.rsa.pub
fi

if [ ! -d "$INPUT_DIR" ]; then
    exit 2
fi

SYSTEM_MAP=$(find "$INPUT_DIR/boot" -name "System.map-*" | head -n 1)
if [ -z "$SYSTEM_MAP" ]; then
    exit 2
fi

FILENAME=$(basename "$SYSTEM_MAP")
VERSION_RAW=$(echo "$FILENAME" | sed 's/System.map-//')
PKG_VER="${VERSION_RAW%%-*}"
PKG_REL=0

echo ">>> build version: $PKG_VER"

BUILD_ROOT="./build/kernel-pkg"

cd "$BUILD_ROOT"

cat <<EOF > APKBUILD
# Generated by pack-kernel.sh
pkgname="$PKG_NAME"
pkgver="$PKG_VER"
pkgrel="$PKG_REL"
maintainer="$MAINTAINER"
pkgdesc="Custom pre-built Linux kernel $VERSION_RAW"
url="https://kernel.org"
arch="noarch"
license="GPL-2.0-only"
options="!check !strip !tracedeps"
depends="mkinitfs kmod"
makedepends=""
source=""

package() {
    local external_src="\$startdir/kernel-bin"
    msg "Copying files from \$external_src..."
    
    mkdir -p "\$pkgdir/boot"
    if [ -d "\$external_src/boot" ]; then
        cp -a "\$external_src/boot/"* "\$pkgdir/boot/"
    fi
    
    mkdir -p "\$pkgdir/lib/modules"
    if [ -d "\$external_src/lib/modules" ]; then
        cp -a "\$external_src/lib/modules/"* "\$pkgdir/lib/modules/"
    fi
}
EOF

echo ">>> gen checksum..."
abuild -F checksum

echo ">>> start build..."

abuild -r -d -F || true

APK_PATH="$HOME/packages/build/$(uname -m)/$PKG_NAME-$PKG_VER-r$PKG_REL.apk"

if [ -f ${APK_PATH} ];then
    rm -f ../$PKG_NAME-$PKG_VER-r$PKG_REL.apk
    mv ${APK_PATH} ..
    rm -rf $HOME/packages
    echo "apk add --allow-untrusted $PKG_NAME-$PKG_VER-r$PKG_REL.apk"
else
    echo "failed"
    exit 2
fi

