#!/usr/bin/env bash
set -Eeuo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=scripts/libs/common.sh
source "$PROJECT_ROOT/scripts/libs/common.sh"

usage() {
	cat <<'EOF'
Usage: scripts/libs/kernel-pkg.sh --board NAME

Create signed Alpine linux-<flavor>, linux-<flavor>-dev,
linux-<flavor>-doc, and linux-headers packages plus a signed local APK
repository.
EOF
}

board=""
kernel_flavor=""
kernel_url=""
KERNEL_FLAVOR=""
KERNEL_ABI_RELEASE=""
KERNEL_PKGVER=""
KERNEL_PKGREL=""
KERNEL_APK_ARCH=""
KERNEL_BOARD=""
while (($#)); do
	case "$1" in
		--board)
			require_arg_value "$1" "${2:-}"
			board="$2"
			shift 2
			;;
		-h | --help) usage; exit 0 ;;
		*) die "Unknown option: $1" ;;
	esac
done
[[ -n "$board" ]] || die "--board is required."

init_logging kernel-package
enable_error_trap
require_root
load_board_config "$board"
require_commands abuild abuild-sign apk cmp find install openssl sed

package_root="$WORK_DIR/kernel-pkg"
metadata_file="$package_root/kernel.env"
template="$PROJECT_ROOT/packaging/kernel/APKBUILD.in"
repository_root="$WORK_DIR/packages"
repository_dir="$repository_root/aarch64"
key_dir="$WORK_DIR/keys"
private_key="${PACKAGER_PRIVKEY:-$key_dir/alpine-sbc.rsa}"
public_key="$private_key.pub"

[[ -f "$metadata_file" ]] || die "Kernel metadata is missing; run scripts/mklinux.sh first."
# The file is generated by mklinux.sh and contains only single-quoted scalar assignments.
# shellcheck disable=SC1090
source "$metadata_file"

[[ "$KERNEL_BOARD" == "$board" ]] || die "Staged kernel belongs to '$KERNEL_BOARD', not '$board'."
[[ "$KERNEL_FLAVOR" == "$kernel_flavor" ]] || die "Kernel flavor metadata does not match the board configuration."
[[ "$KERNEL_APK_ARCH" == aarch64 ]] || die "Only aarch64 APK output is supported."
for directory in kernel-bin kernel-dev-bin kernel-doc-bin kernel-headers-bin; do
	[[ -d "$package_root/$directory" ]] || die "Missing package staging directory: $package_root/$directory"
done
[[ -f "$template" ]] || die "APKBUILD template not found: $template"

mkdir -p "$key_dir" "$repository_dir"
if [[ ! -f "$private_key" ]]; then
	log_info "Generating repository signing key: $private_key"
	openssl genrsa -out "$private_key" 2048
fi
# abuild calls `apk index` after packaging. apk verifies every input APK before
# indexing it, so the matching public key must already be trusted by the host.
# This is the same installation step performed by `abuild-keygen --install`.
prepare_apk_signing_key "$private_key" "$public_key" /etc/apk/keys

escape_sed() { printf '%s' "$1" | sed 's/[&|\\]/\\&/g'; }
sed \
	-e "s|@FLAVOR@|$(escape_sed "$KERNEL_FLAVOR")|g" \
	-e "s|@ABI_RELEASE@|$(escape_sed "$KERNEL_ABI_RELEASE")|g" \
	-e "s|@PKGVER@|$(escape_sed "$KERNEL_PKGVER")|g" \
	-e "s|@PKGREL@|$(escape_sed "$KERNEL_PKGREL")|g" \
	-e "s|@BOARD@|$(escape_sed "$KERNEL_BOARD")|g" \
	-e "s|@KERNEL_URL@|$(escape_sed "$kernel_url")|g" \
	-e "s|@APK_ARCH@|$(escape_sed "$KERNEL_APK_ARCH")|g" \
	"$template" > "$package_root/APKBUILD"

rm -f "$repository_dir"/linux-"$KERNEL_FLAVOR"-*.apk \
	"$repository_dir"/linux-headers-*.apk \
	"$repository_dir"/APKINDEX.tar.gz
mkdir -p "$repository_root/abuild-output"
find "$repository_root/abuild-output" -type f \
	-name "linux-$KERNEL_FLAVOR-*.apk" -delete
find "$repository_root/abuild-output" -type f \
	-name 'linux-headers-*.apk' -delete

log_info "Building signed Alpine kernel packages"
# build.sh intentionally uses `apk add --no-cache`, which removes the index
# cache after installing host tools.  abuild -r resolves the APKBUILD's
# makedepends through apk and therefore needs a current local index here.
log_info "Refreshing Alpine package indexes for abuild dependency resolution"
apk update
(
	cd "$package_root"
	export PACKAGER_PRIVKEY="$private_key"
	export REPODEST="$repository_root/abuild-output"
	abuild -F -r
)

mapfile -d '' built_packages < <(
	find "$repository_root/abuild-output" -type f \
		\( -name "linux-$KERNEL_FLAVOR-*.apk" \
		-o -name "linux-headers-$KERNEL_PKGVER-r$KERNEL_PKGREL.apk" \) -print0
)
((${#built_packages[@]} == 4)) \
	|| die "Expected exactly four current kernel APKs; found ${#built_packages[@]}."
cp -f "${built_packages[@]}" "$repository_dir/"

log_info "Creating signed local APK repository index"
(
	cd "$repository_dir"
	apk index -o APKINDEX.tar.gz ./*.apk
	abuild-sign -k "$private_key" APKINDEX.tar.gz
)

main_apk="$repository_dir/linux-$KERNEL_FLAVOR-$KERNEL_PKGVER-r$KERNEL_PKGREL.apk"
dev_apk="$repository_dir/linux-$KERNEL_FLAVOR-dev-$KERNEL_PKGVER-r$KERNEL_PKGREL.apk"
doc_apk="$repository_dir/linux-$KERNEL_FLAVOR-doc-$KERNEL_PKGVER-r$KERNEL_PKGREL.apk"
headers_apk="$repository_dir/linux-headers-$KERNEL_PKGVER-r$KERNEL_PKGREL.apk"
[[ -f "$main_apk" && -f "$dev_apk" && -f "$doc_apk" && -f "$headers_apk" ]] \
	|| die "One or more expected kernel packages are missing from $repository_dir."

cat > "$repository_root/kernel-packages.env" <<EOF
KERNEL_PACKAGE='linux-$KERNEL_FLAVOR'
KERNEL_DEV_PACKAGE='linux-$KERNEL_FLAVOR-dev'
KERNEL_DOC_PACKAGE='linux-$KERNEL_FLAVOR-doc'
KERNEL_HEADERS_PACKAGE='linux-headers'
KERNEL_FLAVOR='$KERNEL_FLAVOR'
KERNEL_PKGVER='$KERNEL_PKGVER'
KERNEL_PKGREL='$KERNEL_PKGREL'
KERNEL_ABI_RELEASE='$KERNEL_ABI_RELEASE'
KERNEL_REPOSITORY='$repository_dir'
KERNEL_PUBLIC_KEY='$public_key'
EOF

log_info "Kernel repository ready: $repository_dir"
log_info "Packages: $(find "$repository_dir" -maxdepth 1 -name '*.apk' -printf '%f ' | sort)"
